import smtplib
from email.message import EmailMessage
import datetime
import os
#--Mailing--
def SendMails(ResultsTable,StudName,Roll,StudMail,SemDetails,Department,SemSGPA,SemCGPA):
    with smtplib.SMTP(os.getenv('MServer',default='smtp-mail.outlook.com'),os.getenv('MPort',default='587')) as smtp:
        #print(datetime.datetime.now())
        smtp.starttls()
        smtp.login(os.getenv('Mail'),os.getenv('MPass'))
        MainMsg=EmailMessage()
        MainMsg['Subject']=f'{StudName} Your Results Are Scrapped'
        MainMsg['From']=os.getenv('Mail')
        MainMsg['To']=StudMail
        
        MarksHtml=f"""\
        <!DOCTYPE html>
        <html>
        <body>
        <p style="text-align:center"><img alt="" src="https://svceta.org/BeesERP/Images/header.jpg" style="height:70px; width:671px" /></p>
        <p><strong><span style="font-size:16px">Student Name : {StudName}&nbsp;&nbsp;</span></strong></p>
        <p><strong><span style="font-size:16px">RollNumber : {Roll}&nbsp;&nbsp;</span></strong></p>
        <p><strong><span style="font-size:16px">Department : {Department}&nbsp;&nbsp;</span></strong></p>
        <p><strong><span style="font-size:16px">{SemDetails}&nbsp;&nbsp;</span></strong></p>
        <p>&nbsp;</p>
        {ResultsTable}
        <p>&nbsp;</p>
        <div align="right" style="color:Black;font-size:large;font-weight:bold;">{SemSGPA}     {SemCGPA}</div>
        <p style="text-align:right"><span style="color:#ffffff"><span style="background-color:#000000">--Generated by Team </span></span><a href="https://t.me/I_AmKarthi"><span style="color:#ffffff"><span style="background-color:#000000">Villlain4U</span></span></a><span style="color:#ffffff"><span style="background-color:#000000">--</span></span><br />
        &nbsp;</p>
        </body>
        </html>
        """
        MainMsg.add_alternative(MarksHtml,subtype='html')
        smtp.send_message(MainMsg)
        print("Mail Sent To:"+StudMail+" - "+datetime.datetime.now())

